%:
	./checker $*-*.c $(file)

2: file=0-p*.c
3: file=0-p*.c
4: file=3-a*.c 0-p*.c 
5: file=3-a*.c 0-p*.c 
6: file=3-a*.c 0-p*.c 5-f*.c
7: file=3-a*.c 0-p*.c 5-f*.c
8: file=3-a*.c 0-p*.c 5-f*.c
9: file=3-a*.c 0-p*.c 5-f*.c
10: file=3-a*.c 0-p*.c 5-f*.c
